<?php

/*
 * Function connects to the bike database
 *
 * @return PDO returns the database contents
 *
 */
function dbConn() :PDO{
    $db = new PDO('mysql:host=db; dbname=calumCollection', 'root', 'password');
    $db->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
    return $db;
}

/*
 * Grabs all the data for each bike
 *
 * @param $db PDO the myBikes DB
 *
 * @return array the data for each bike
 */
function getData(PDO $db) :array {
    $query = $db->prepare("SELECT `manufacturer`, `model`, `wheelset`, `groupset`, `image` FROM `myBikes`;");
    $query->execute();
    $result = $query->fetchAll();
    return $result;
}



/*
 * Takes data from getData output array and displays as HTML to be called into index.php
 *
 * @param $bikes array of the bikes data selected from getData
 *
 * @return a string of HTML code to be inserted to index.php to display on front end
 */
function getBike(array $bikes) :string
{
    if (count($bikes[0]) === 5) {
        $output = '';
        foreach ($bikes as $bike) {
            $output .=
                '<div class="tableContent">' .
                '<div class = "image"><img src="' . $bike['image'] . '" alt="picture of bike">' . '</img>' . '</div>' .
                '<div><p>' . $bike['manufacturer'] . '</p>' . '</div>' .
                '<div><p>' . $bike['model'] . '</p>' . '</div>' .
                '<div><p>' . $bike['wheelset'] . '</p>' . '</div>' .
                '<div><p>' . $bike['groupset'] . '</p>' . '</div>' .
                '</div>';
        }
        return $output;
    } else {
        return 'Please check bike data is complete.';
    }
}

/*
 * Takes the array generated by user on formPage.php and adds to database
 *
 * @param $values array of the user's input from formPage.php
 *
 * @param $connection array of current contents of DB we're inserting into
 *
 * @returns user-generated data to DB
 */
function addDataToDb(array $values, PDO $connection)
{
    $query = $connection->prepare("INSERT INTO `myBikes` (`manufacturer`, `model`, `wheelset`, `groupset`, `image`)
    VALUES (:manufacturer, :model, :wheelset, :groupset, :image)");
    $manufacturer = $values['manufacturer'];
    $model = $values['model'];
    $wheelset = $values['wheelset'];
    $groupset = $values['groupset'];
    $image = $values['image'];
    $query->bindParam(':manufacturer', $manufacturer, PDO::PARAM_STR, 255);
    $query->bindParam(':model', $model, PDO::PARAM_STR, 255);
    $query->bindParam(':wheelset', $wheelset, PDO::PARAM_STR, 255);
    $query->bindParam(':groupset', $groupset, PDO::PARAM_STR, 255);
    $query->bindParam(':image', $image, PDO::PARAM_STR, 255);
    $isItComplete = $query->execute();
    return $isItComplete;
}

?>